### PR TITLE
Implement correct retry logic, with jitter by default

### LINKED ISSUE #5: Fix retry logic to AWS specifications, add full jitter by default
The current behavior is waiting twice as long as it should (at least per AWS recommendations).  200ms, 400ms, 800ms - instead of 100ms, 200ms, 400ms.

In addition, https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/ makes a compelling case for adding jitter by default.  Many of our retries are in the context of parallel execution (especially with batch jobs etc).

See https://checkdigit.slack.com/archives/C020WPN39L1/p1658968673467829 for more context.

### PR DESCRIPTION
**Pull request by carlansley**
Fixes #5.

Using MAJOR label so that it is not pulled in accidentally by `npm install`.

### CODE REVIEW

**Review by adcreare — APPROVED** [review]
LGTM - I think this is actually a really good change and will also help reduce throttle events on large concurrent aws operations

**Review by yeshima — APPROVED** [review]

**Review by bobwieler — APPROVED** [review]
lgtm

**Review by ramaghanta — APPROVED** [review]
lgtm

**Review by greg-w101 — APPROVED** [review]
lgtm

**Review by lukebrdn — APPROVED** [review]
lgtm

**Pull request merged**
